version: '3.8'

services:
  master_postgres:
    image: postgres:13.3
    container_name: master_postgres-2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5434:5432'